//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUTHU
    {
        public string MaPhuThu { get; set; }
        public string TenPhuThu { get; set; }
        public Nullable<int> STT_KH { get; set; }
        public Nullable<double> TyLePhuThu { get; set; }
    }
}
